// Generated by CoffeeScript 1.7.1
(function() {
  var browser, loadfile, window;

  browser = require('./env/Browser');

  window = browser.window;

  loadfile = function(path) {
    var define, g, temp;
    temp = null;
    define = function(obj) {
      return temp = obj;
    };
    g = global;
    g.define = define;
    require.apply(g, arguments);
    return temp;
  };

  describe("Lang file generated format", function() {
    return it("should not contains Chinese char in English lang file", function(done) {
      var english, key, sub, subvalue, value;
      english = loadfile("../src/nls/en-us/lang");
      for (key in english) {
        value = english[key];
        for (sub in value) {
          subvalue = value[sub];
          if (subvalue.match(/[\u4e00-\u9fa5]/)) {
            console.log(key, sub, subvalue);
            done(new Error("Chinese chars shouldn't appear here."));
            return;
          }
        }
      }
      console.log("----------------========Chinese Chars Check Passed========-------------------");
      return done();
    });
  });

}).call(this);

//# sourceMappingURL=lang.map
