// Generated by CoffeeScript 1.7.1
(function() {
  var browser, loadfile, window;

  browser = require('./env/Browser');

  window = browser.window;

  loadfile = function(path) {
    var define, g, temp;
    temp = null;
    define = function(obj) {
      return temp = obj;
    };
    g = global;
    g.define = define;
    require.apply(g, arguments);
    return temp;
  };

  describe("Lang file generated format", function() {
    return it("should not contains Chinese char in English lang file", function(done) {
      var english, key, sub, subvalue, value;
      english = loadfile("../src/nls/en-us/lang");
      for (key in english) {
        value = english[key];
        console.log("Checking " + key + " of English lang file.");
        for (sub in value) {
          subvalue = value[sub];
          if (subvalue.match(/[\u4e00-\u9fa5]/)) {
            console.log(key, sub, subvalue);
            done(new Error("Chinese chars shouldn't appear here."));
            return;
          }
        }
      }
      console.log("----------------========Chinese Chars Check Passed========-------------------");
      return done();
    });
  });

  describe("should not contains english symbol in Chinese lang.", function() {
    var chinese;
    chinese = loadfile("../src/nls/zh-cn/lang");
    return it("should", function(done) {
      var fail, key, sub, subvalue, value;
      fail = false;
      for (key in chinese) {
        value = chinese[key];
        console.log("Checking " + key + " of Chinese file...");
        for (sub in value) {
          subvalue = value[sub];
          if (subvalue.match(/[\,\!]/)) {
            if (sub !== 'DATE_FORMAT_MONTHS' && sub !== 'DATE_FORMAT_MON' && sub !== 'DATE_FORMAT_WEEK' && sub !== 'DATE_FORMAT_WEK') {
              console.log(key, sub, subvalue);
              fail = true;
            }
          }
        }
      }
      if (fail) {
        return done(new Error("Chinese file check failed."));
      } else {
        return done();
      }
    });
  });

}).call(this);

//# sourceMappingURL=lang.map
