define(['ApiRequestDefs'], function( ApiRequestDefs ){
	var Apis = {
		'nova_List'                         : { url:'/os/nova/v2_0/nova/',	method:'List',	params:['username', 'session_id', 'region']   },
		'nova_V2_Info'                      : { url:'/os/nova/v2_0/nova/',	method:'V2_Info',	params:['username', 'session_id', 'region']   },
		'nova_V2_Extension'                 : { url:'/os/nova/v2_0/nova/',	method:'V2_Extension',	params:['username', 'session_id', 'region', 'alias']   },
		'nova_V2_Limits'                    : { url:'/os/nova/v2_0/nova/',	method:'V2_Limits',	params:['username', 'session_id', 'region', 'spec_tenant_id']   },
		'agent_List'                        : { url:'/os/nova/v2_0/agent/',	method:'List',	params:['username', 'session_id', 'region']   },
		'agent_Create'                      : { url:'/os/nova/v2_0/agent/',	method:'Create',	params:['username', 'session_id', 'region', 'agent']   },
		'agent_Delete'                      : { url:'/os/nova/v2_0/agent/',	method:'Delete',	params:['username', 'session_id', 'region']   },
		'agent_Update'                      : { url:'/os/nova/v2_0/agent/',	method:'Update',	params:['username', 'session_id', 'region', 'agent_id', 'agent']   },
		'aggregate_List'                    : { url:'/os/nova/v2_0/aggregate/',	method:'List',	params:['username', 'session_id', 'region']   },
		'aggregate_Info'                    : { url:'/os/nova/v2_0/aggregate/',	method:'Info',	params:['username', 'session_id', 'region', 'ids']   },
		'aggregate_Create'                  : { url:'/os/nova/v2_0/aggregate/',	method:'Create',	params:['username', 'session_id', 'region', 'aggregate']   },
		'aggregate_Delete'                  : { url:'/os/nova/v2_0/aggregate/',	method:'Delete',	params:['username', 'session_id', 'region', 'aggregate_id']   },
		'aggregate_Update'                  : { url:'/os/nova/v2_0/aggregate/',	method:'Update',	params:['username', 'session_id', 'region', 'aggregate_id', 'specs']   },
		'aggregate_SetAggregateMetadata'    : { url:'/os/nova/v2_0/aggregate/',	method:'SetAggregateMetadata',	params:['username', 'session_id', 'region', 'aggregate_id', 'metadata']   },
		'aggregate_AddHost'                 : { url:'/os/nova/v2_0/aggregate/',	method:'AddHost',	params:['username', 'session_id', 'region', 'aggregate_id', 'host_id']   },
		'aggregate_RemoveHost'              : { url:'/os/nova/v2_0/aggregate/',	method:'RemoveHost',	params:['username', 'session_id', 'region', 'aggregate_id', 'host_id']   },
		'cloudpipe_List'                    : { url:'/os/nova/v2_0/cloudpipe/',	method:'List',	params:['username', 'session_id', 'region']   },
		'cloudpipe_Create'                  : { url:'/os/nova/v2_0/cloudpipe/',	method:'Create',	params:['username', 'session_id', 'region', 'project_id']   },
		'cloudpipe_Update'                  : { url:'/os/nova/v2_0/cloudpipe/',	method:'Update',	params:['username', 'session_id', 'region', 'specs']   },
		'flavor_List'                       : { url:'/os/nova/v2_0/flavor/',	method:'List',	params:['username', 'session_id', 'region', 'min_disk', 'min_ram', 'marker', 'limit']   },
		'flavor_Info'                       : { url:'/os/nova/v2_0/flavor/',	method:'Info',	params:['username', 'session_id', 'region', 'ids']   },
		'flavor_Create'                     : { url:'/os/nova/v2_0/flavor/',	method:'Create',	params:['username', 'session_id', 'region', 'flavor']   },
		'flavor_ListFlavorTenants'          : { url:'/os/nova/v2_0/flavor/',	method:'ListFlavorTenants',	params:['username', 'session_id', 'region', 'flavor_id']   },
		'flavor_AddTenantAccess'            : { url:'/os/nova/v2_0/flavor/',	method:'AddTenantAccess',	params:['username', 'session_id', 'region', 'flavor_id', 'access']   },
		'flavor_RemoveTenantAccess'         : { url:'/os/nova/v2_0/flavor/',	method:'RemoveTenantAccess',	params:['username', 'session_id', 'region', 'flavor_id', 'access']   },
		'flavor_ListFlavorExtraSpecs'       : { url:'/os/nova/v2_0/flavor/',	method:'ListFlavorExtraSpecs',	params:['username', 'session_id', 'region', 'key_id']   },
		'flavor_CreateFlavorExtraSpecs'     : { url:'/os/nova/v2_0/flavor/',	method:'CreateFlavorExtraSpecs',	params:['username', 'session_id', 'region', 'specs']   },
		'flavor_DeleteFlavorExtraSpecs'     : { url:'/os/nova/v2_0/flavor/',	method:'DeleteFlavorExtraSpecs',	params:['username', 'session_id', 'region', 'key_id']   },
		'host_List'                         : { url:'/os/nova/v2_0/host/',	method:'List',	params:['username', 'session_id', 'region', 'service', 'zone']   },
		'host_Info'                         : { url:'/os/nova/v2_0/host/',	method:'Info',	params:['username', 'session_id', 'region', 'host_names']   },
		'hypervisor_List'                   : { url:'/os/nova/v2_0/hypervisor/',	method:'List',	params:['username', 'session_id', 'region']   },
		'hypervisor_Info'                   : { url:'/os/nova/v2_0/hypervisor/',	method:'Info',	params:['username', 'session_id', 'region', 'hypervisor_hostname', 'list_servers']   },
		'hypervisor_Statistics'             : { url:'/os/nova/v2_0/hypervisor/',	method:'Statistics',	params:['username', 'session_id', 'region']   },
		'image_List'                        : { url:'/os/nova/v2_0/image/',	method:'List',	params:['username', 'session_id', 'region', 'changes_since', 'server', 'name', 'status', 'marker', 'limit', 'type']   },
		'image_Info'                        : { url:'/os/nova/v2_0/image/',	method:'Info',	params:['username', 'session_id', 'region', 'ids']   },
		'image_CreateImageMetadata'         : { url:'/os/nova/v2_0/image/',	method:'CreateImageMetadata',	params:['username', 'session_id', 'region', 'image_id', 'metadata']   },
		'image_GetImageMetadata'            : { url:'/os/nova/v2_0/image/',	method:'GetImageMetadata',	params:['username', 'session_id', 'region', 'image_id', 'metadata_key']   },
		'image_UpdateImageMetadata'         : { url:'/os/nova/v2_0/image/',	method:'UpdateImageMetadata',	params:['username', 'session_id', 'region', 'image_id', 'metadata']   },
		'image_DeleteImageMetadata'         : { url:'/os/nova/v2_0/image/',	method:'DeleteImageMetadata',	params:['username', 'session_id', 'region', 'image_id', 'metadata_key']   },
		'interface_List'                    : { url:'/os/nova/v2_0/interface/',	method:'List',	params:['username', 'session_id', 'region', 'server_id', 'attachment_id']   },
		'interface_Info'                    : { url:'/os/nova/v2_0/interface/',	method:'Info',	params:['username', 'session_id', 'region', 'server_id', 'attachment_ids']   },
		'interface_Create'                  : { url:'/os/nova/v2_0/interface/',	method:'Create',	params:['username', 'session_id', 'region', 'server_id', 'interface']   },
		'interface_Delete'                  : { url:'/os/nova/v2_0/interface/',	method:'Delete',	params:['username', 'session_id', 'region', 'server_id', 'attachment_id']   },
		'interface_ListVirtualInterface'    : { url:'/os/nova/v2_0/interface/',	method:'ListVirtualInterface',	params:['username', 'session_id', 'region', 'server_id']   },
		'ip_ListServerAddresses'            : { url:'/os/nova/v2_0/ip/',	method:'ListServerAddresses',	params:['username', 'session_id', 'region', 'server_id', 'network_label']   },
		'ip_ListFixedAddresses'             : { url:'/os/nova/v2_0/ip/',	method:'ListFixedAddresses',	params:['uesrname', 'session_id', 'region', 'addr_id']   },
		'ip_ReserveFixedAddress'            : { url:'/os/nova/v2_0/ip/',	method:'ReserveFixedAddress',	params:['username', 'session_id', 'region', 'addr_id']   },
		'ip_ListDomainEntries'              : { url:'/os/nova/v2_0/ip/',	method:'ListDomainEntries',	params:['username', 'session_id', 'region']   },
		'ip_ListDNSEntries'                 : { url:'/os/nova/v2_0/ip/',	method:'ListDNSEntries',	params:['username', 'session_id', 'region', 'domain', 'dns_name', 'dns_ip']   },
		'ip_ListFloatingAddressPools'       : { url:'/os/nova/v2_0/ip/',	method:'ListFloatingAddressPools',	params:['uesrname', 'session_id', 'region']   },
		'ip_ListFloatingAddresses'          : { url:'/os/nova/v2_0/ip/',	method:'ListFloatingAddresses',	params:['username', 'session_id', 'region', 'addr_id']   },
		'ip_ListFloatingAddressesBulk'      : { url:'/os/nova/v2_0/ip/',	method:'ListFloatingAddressesBulk',	params:['username', 'session_id', 'region', 'host_name']   },
		'keypair_List'                      : { url:'/os/nova/v2_0/keypair/',	method:'List',	params:['username', 'session_id', 'region', 'keypair_name']   },
		'keypair_Info'                      : { url:'/os/nova/v2_0/keypair/',	method:'Info',	params:['username', 'session_id', 'region', 'keypair_names']   },
		'keypair_Create'                    : { url:'/os/nova/v2_0/keypair/',	method:'Create',	params:['username', 'session_id', 'region', 'keypair_name', 'public_key']   },
		'keypair_Delete'                    : { url:'/os/nova/v2_0/keypair/',	method:'Delete',	params:['username', 'session_id', 'region', 'keypair_name']   },
		'network_List'                      : { url:'/os/nova/v2_0/network/',	method:'List',	params:['username', 'session_id', 'region', 'network_id']   },
		'network_Info'                      : { url:'/os/nova/v2_0/network/',	method:'Info',	params:['username', 'session_id', 'region', 'network_ids']   },
		'securitygroup_List'                : { url:'/os/nova/v2_0/sg/',	method:'List',	params:['username', 'session_id', 'region', 'server_id', 'sg_id']   },
		'securitygroup_ListDefaultRules'    : { url:'/os/nova/v2_0/sg/',	method:'ListDefaultRules',	params:['username', 'session_id', 'region', 'default_sg_id']   },
		'server_List'                       : { url:'/os/nova/v2_0/server/',	method:'List',	params:['username', 'session_id', 'region', 'changes_since', 'image', 'flavor', 'name', 'marker', 'limit', 'status', 'host']   },
		'server_Info'                       : { url:'/os/nova/v2_0/server/',	method:'Info',	params:['username', 'session_id', 'region', 'ids']   },
		'server_CreateServerMetadata'       : { url:'/os/nova/v2_0/server/',	method:'CreateServerMetadata',	params:['username', 'session_id', 'region', 'server_id', 'metadata']   },
		'server_GetServerMetadata'          : { url:'/os/nova/v2_0/server/',	method:'GetServerMetadata',	params:['username', 'session_id', 'region', 'server_id', 'metadata_key']   },
		'server_UpdateServerMetadata'       : { url:'/os/nova/v2_0/server/',	method:'UpdateServerMetadata',	params:['username', 'session_id', 'region', 'server_id', 'metadata']   },
		'server_DeleteServerMetadata'       : { url:'/os/nova/v2_0/server/',	method:'DeleteServerMetadata',	params:['username', 'session_id', 'region', 'server_id', 'metadata_key']   },
		'server_GetConsole'                 : { url:'/os/nova/v2_0/server/',	method:'GetConsole',	params:['username', 'session_id', 'region', 'server_id', 'action', 'specs']   },
		'server_GetServerPassword'          : { url:'/os/nova/v2_0/server/',	method:'GetServerPassword',	params:['username', 'session_id', 'region', 'server_id']   },
		'server_DeleteServerPassword'       : { url:'/os/nova/v2_0/server/',	method:'DeleteServerPassword',	params:['username', 'session_id', 'region', 'server_id']   },
		'server_GetServerDiagnostics'       : { url:'/os/nova/v2_0/server/',	method:'GetServerDiagnostics',	params:['username', 'session_id', 'region', 'server_id']   },
		'server_List'                       : { url:'/os/nova/v2_0/server/',	method:'List',	params:['username', 'session_id', 'region']   },
		'server_Info'                       : { url:'/os/nova/v2_0/server/',	method:'Info',	params:['username', 'session_id', 'region', 'ids']   },
		'service_List'                      : { url:'/os/nova/v2_0/service/',	method:'List',	params:['username', 'session_id', 'region', 'is_disabled']   },
		'snapshot_List'                     : { url:'/os/nova/v2_0/snapshot/',	method:'List',	params:['username', 'session_id', 'region']   },
		'snapshot_Info'                     : { url:'/os/nova/v2_0/snapshot/',	method:'Info',	params:['username', 'session_id', 'region', 'snapshot_id']   },
		'v2_CreateRootCertificate'          : { url:'/os/nova/v2_0/v2/',	method:'CreateRootCertificate',	params:['username', 'session_id', 'region']   },
		'v2_GetRootCertificate'             : { url:'/os/nova/v2_0/v2/',	method:'GetRootCertificate',	params:['username', 'session_id', 'region']   },
		'v2_ListTenantUsage'                : { url:'/os/nova/v2_0/v2/',	method:'ListTenantUsage',	params:['username', 'session_id', 'region', 'spec_tenant_id']   },
		'volume_List'                       : { url:'/os/nova/v2_0/volume/',	method:'List',	params:['username', 'session_id', 'region']   },
		'volume_Info'                       : { url:'/os/nova/v2_0/volume/',	method:'Info',	params:['username', 'session_id', 'region', 'volume_id']   },
		'volume_ListVolumeType'             : { url:'/os/nova/v2_0/volume/',	method:'ListVolumeType',	params:['username', 'session_id', 'region', 'volume_type_id']   },
		'volume_ListVolumeAttachment'       : { url:'/os/nova/v2_0/volume/',	method:'ListVolumeAttachment',	params:['username', 'session_id', 'region', 'server_id', 'attachment_id']   },
	}

	for ( var i in Apis ) {
		ApiRequestDefs.Defs[ i ] = Apis[ i ];
	}

});
