// Generated by CoffeeScript 1.6.2
module.exports = {};

module.exports.create = function() {
  var file, gutil, http, nstatic, server;

  gutil = require("gulp-util");
  gutil.log(gutil.colors.bgBlue(" Creating File Server... "));
  nstatic = require("node-static");
  http = require("http");
  file = new nstatic.Server("./src", {
    "Cache-Control": "no-cache"
  });
  server = http.createServer(function(request, response) {
    request.addListener('end', function() {
      var url;

      url = request.url;
      if (url === "/") {
        file.serveFile("/ide.html", 200, {
          "Cache-Control": "no-cache"
        }, request, response);
      } else {
        if (url[url.length - 1] === "/") {
          file.serveFile("/ide.html", 301, {
            "Location": url.substring(0, url.length - 1)
          }, request, response);
        } else if (url.lastIndexOf(".html") !== -1) {
          file.serve(request, response);
        } else if (url.indexOf("/", 1) === -1) {
          file.serveFile(url + ".html", 200, {
            "Cache-Control": "no-cache"
          }, request, response);
        } else {
          file.serve(request, response);
        }
      }
      return null;
    });
    return request.resume();
  });
  server.listen("3000", "127.0.0.1");
  return null;
};
