// Generated by CoffeeScript 1.6.2
(function() {
  var defaultHeader;

  module.exports = {};

  defaultHeader = {
    "Cache-Control": "no-cache"
  };

  module.exports.create = function() {
    var file, gutil, http, nstatic, server;

    gutil = require("gulp-util");
    nstatic = require("node-static");
    http = require("http");
    gutil.log(gutil.colors.bgBlue(" Creating File Server... "));
    file = new nstatic.Server("./src", {
      cache: false,
      headers: defaultHeader
    });
    server = http.createServer(function(request, response) {
      request.addListener('end', function() {
        var errorHandler, filePath, url;

        url = request.url;
        if (url === "/") {
          filePath = "/ide.html";
        } else if (url[url.length - 1] === "/") {
          response.writeHead(301, {
            "Location": url.substring(0, url.length - 1)
          });
          response.end();
          return;
        } else if (url.indexOf(".", 1) === -1) {
          filePath = url + ".html";
        }
        errorHandler = function(e) {
          console.log("[ServerError]", e.message, request.url);
          response.writeHead(404);
          response.end();
          return null;
        };
        if (filePath) {
          file.serveFile(filePath, 200, defaultHeader, request, response).addListener("error", errorHandler);
        } else {
          file.serve(request, response).addListener("error", errorHandler);
        }
        return null;
      });
      request.resume();
      return null;
    });
    server.listen("3000", "127.0.0.1");
    return null;
  };

}).call(this);
