// Generated by CoffeeScript 1.7.1
(function() {
  var window;

  window = require("../env/Browser").window;

  describe("UI.ModalPlus Test", function() {
    return it("should not render the second modal if the first modal hasn't finished rendering", function(done) {
      return window.require(['UI.modalplus'], function(Modal) {
        var modalA, modalB;
        modalA = new Modal({
          title: "test A"
        });
        modalB = new Modal({
          title: "test B"
        });
        console.log(modalA, modalB.isOpen());
        if (modalB.isOpen()) {
          return done(new Error("Second modal shouldn't render."));
        } else {
          return done();
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=modal.map
