define ['MC',
		'lib/aws/aws',
		'lib/aws/ec2/instance',
		'lib/aws/ec2/ebs',
		'lib/aws/ec2/ami',
		'lib/aws/elb/elb',
		'lib/aws/vpn/vpn',
		'lib/aws/vpc/networkacl',
		'lib/aws/ec2/securitygroup',
		'lib/aws/ec2/keypair',
		'lib/aws/vpc/eni',
		'lib/aws/vpc/vpc',
		'lib/aws/vpc/subnet',
		'lib/aws/vpc/rtb',
		'lib/aws/autoscaling/asg',
		'lib/aws/autoscaling/launchconfiguration',
		'lib/aws/vpc/igw',
		'lib/aws/ec2/eip'], (MC, aws_handler, aws_handler_instance, aws_handler_ebs, aws_handler_ami, aws_handler_elb, aws_handler_vpn, aws_handler_acl, aws_handler_securitygroup, aws_handler_keypair,aws_handler_eni, aws_handler_vpc, aws_handler_subnet, aws_handler_rtb, aws_handler_asg, aws_handler_lc, aws_handler_igw, aws_handler_eip) ->
	MC.aws = {
		instance: aws_handler_instance,
		asg: aws_handler_asg,
		lc : aws_handler_lc,
		aws: aws_handler,
		ebs: aws_handler_ebs,
		ami: aws_handler_ami,
		elb: aws_handler_elb,
		vpn: aws_handler_vpn,
		acl: aws_handler_acl,
		sg: aws_handler_securitygroup,
		kp: aws_handler_keypair,
		eni: aws_handler_eni,
		vpc: aws_handler_vpc,
		subnet: aws_handler_subnet,
		rtb: aws_handler_rtb,
		igw: aws_handler_igw,
		eip: aws_handler_eip
	}
