define ['MC',
		'lib/aws/aws',
		'lib/aws/ec2/instance',
		'lib/aws/ec2/ebs',
		'lib/aws/elb/elb',
		'lib/aws/vpn/vpn',
		'lib/aws/vpc/networkacl',
		'lib/aws/ec2/securitygroup',
		'lib/aws/ec2/keypair',
		'lib/aws/vpc/eni',
		'lib/aws/vpc/vpc',
		'lib/aws/vpc/subnet',
		'lib/aws/vpc/rtb',
		'lib/aws/autoscaling/asg',
		'lib/aws/autoscaling/launchconfiguration'], (MC, aws_handler, aws_handle_instance, aws_handle_ebs, aws_handle_elb, aws_handle_vpn, aws_handle_acl, aws_handle_securitygroup, aws_handle_keypair,aws_handle_eni, aws_handle_vpc, aws_handle_subnet, aws_handle_rtb, aws_handler_asg, aws_handler_lc) ->
	MC.aws = {
		instance: aws_handle_instance,
		asg: aws_handler_asg,
		lc : aws_handler_lc,
		aws: aws_handler,
		ebs: aws_handle_ebs,
		elb: aws_handle_elb,
		vpn: aws_handle_vpn,
		acl: aws_handle_acl,
		sg: aws_handle_securitygroup,
		kp: aws_handle_keypair,
		eni: aws_handle_eni,
		vpc: aws_handle_vpc,
		subnet: aws_handle_subnet,
		rtb: aws_handle_rtb
	}
